config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope '(:locale)', locale: /fr|nl|en/ do
    root to: 'contents#index'
    resources :contents
    resources :users
    resources :tags
    get '/admin', to: 'pages#admin'
    get '/admin/contents', to: 'contents#admin'
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  ALLOWED_STATUSES = %w[draft published archived].freeze
  ALLOWED_TAGS = %w[Accueil Projet Animations Parrainage Entreprises Produits Bien-être Volontariat 'Sans rubrique'].freeze

  belongs_to :user

  has_one_attached :image
  has_one_attached :image800x800
  has_many_attached :file
  has_many :content_tag, dependent: :destroy
  has_many :tags, through: :content_tag

  validates :title, presence: true
  validates :status, presence: true, inclusion: { in: ALLOWED_STATUSES,
                                                  message: "%{value} n'est pas un statut valide" }

  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/content_tag.rb
class ContentTag < ApplicationRecord
  belongs_to :content
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :content_tag, dependent: :destroy
  has_many :contents, through: :content_tag

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  extend FriendlyId
  friendly_id :username, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_locale

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def set_locale
    I18n.locale = params.fetch(:locale, I18n.default_locale).to_sym
  end

  def default_url_options
    { locale: I18n.locale == I18n.default_locale ? nil : I18n.locale }
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def show
    @content = Content.friendly.find(params[:id])
    authorize @content
  end

  def new
    @content = Content.new
    @tags = Tag.all
    authorize @content
  end

  def create
    @content = Content.new(content_params)
    @content.user = current_user
    @content.save
    authorize @content

    redirect_to content_path(@content)
  end

  def edit
    @tags = Tag.all
    @content = Content.find(params[:id])
    authorize @content
  end

  def update
    @content = Content.find(params[:id])
    @content.update(content_params)
    authorize @content
    redirect_to content_path(@content)
  end

  def destroy
    @content = Content.friendly.find(params[:id])
    @content.destroy
    authorize @content
    redirect_to root_path
  end

  def index
    @contents = policy_scope(Content).where(status: "published").order(:order)
  end

  def admin
    @content = Content.all.order(:order)

    authorize @content
  end

  def related_contents
    @content = Content.find(params[:id])
    @related_tags = @content.tags
  end

  private

  def content_params
    params.require(:content).permit(:title, :status, :teaser, :body, :links, :image, :image800x800, :order, tag_ids: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def admin
  end

  def show
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :find_tag, only: [:update, :edit, :destroy]

  def index
    @tags = policy_scope(Tag).all.sort_by(&:title)
  end

  def new
    @tag = Tag.new
    authorize @tag
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.save
    authorize @tag
  end

  def edit
    authorize @tag
  end

  def update
    @tag.update(tag_params)
    authorize @tag
    redirect_to tags_path
  end

  def destroy
    @tag.destroy
    authorize @tag
    redirect_to tags_path
  end

  private

  def find_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.friendly.find(params[:id])
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contents/admin.html.erb
<div class="container margin-top admin">
  <div class="row">
    <div class="col-8">
      <h1 class="title-admin">Gestion des contenus</h1>
    </div>
    <div class="col-4">
      <%= link_to 'Ajouter un contenu', new_content_path, class:'btn btn-primary btn-right' %>
    </div>
  </div>
  <hr>

    <% @content.each do |c| %>
      <div class="row admin-row">
        <div class="col-2">
          <small><%= c.created_at.strftime("%d.%m.%Y") %></small>
        </div>
        <div class="col-4">
          <%= link_to c.title, content_path(c.id) %>
        </div>
        <div class="col-2">
          <%= c.status %>
        </div>
        <div class="col-2">

        </div>
      <div class="col-1">
        <%= link_to edit_content_path(c.id), title:"Modifier" do %>
          <i class="fas fa-edit fa-fw"></i>
        <% end %>
      </div>
      <div class="col-1">
              <%= button_to "Supprimer", content_path(c.id),
                  method: :delete,
                  data: { confirm: "Veuillez confirmer la suppression !" },
                 :id => "delete", class:"btn btn-danger" %>
      </div>
      </div>
    <% end %>
</div>

app/views/contents/edit.html.erb
<div class="container margin-top">
  <h1 class="title-admin">Modifier : <i><%= @content.title %></i></h1>
  <hr>
  <%= simple_form_for @content, url: content_path, method: :patch do |c| %>
    <%= c.association :tags, collection: @tags, as: :check_boxes, input_html: { multiple: true}, label: 'Rubrique(s)' %>

    <%= c.input :title, label: 'Titre' %>
    <div class="hidden-field">
      <%= c.input :status, label: 'Statut', collection: ['draft', 'published', 'archived'], id: 'status', default:'draft' %>
    </div>
    <%= c.input :teaser, label: 'Teaser' %>
    <%= c.input :body, label:'Corps de texte' %>
    <%= c.input :links, label: 'Liens' %>
    <%= c.input :image, as: :file, label: 'Image pour le format banner' %>
    <%= c.input :image800x800, as: :file, label: 'Image pour le format carré' %>
    <%= c.input :order, label: "Ordre en page d'accueil" %>
    <div class="row article-actions">
      <%= submit_tag "Enregistrer le brouillon", class: "btn btn-secondary", id: "save_draft" %> &nbsp;
      <%= submit_tag "Enregistrer et publier", class: "btn btn-primary", id: "save_published" %>
    </div>
  <% end %>
</div>
<script src="application.js"></script>

app/views/contents/index.html.erb
<div class="home-banner-container">
<div class="home-banner">
</div>
  <div class="home-banner-content">
  <h1 class="headline">Créer du lien entre Nature et Humains </h1>
  </div>
</div>

  <% @contents.each do |c| %>
    <% if c.order == 1 %>
    <div id="projet" class="topic">
      <div class="row align-items-center justify-content-between">
        <div class="col-4">
          <h1><%= c.title %></h1>
            <p class="home">
              <%= c.teaser %> &nbsp; <%= link_to 'En savoir plus...', content_path(c.id), class:"lire-plus" %>
            </p>
        </div>
        <div class="col-6 img-parent">
          <div class="img-custom">
            <div class="grayscale">
              <%= cl_image_tag c.image800x800.key %>
            </div>
          </div>
            <div class="img-hexagone"><img src="<%= image_url("masque-hexagone.png") %>"></div>
        </div>
      </div>
    </div>
      <div class="topic-banner">
        <%= cl_image_tag c.image.key %>
      </div>
    <% end %>
    <% if c.order == 2 %>
    <div id="animations" class="topic">
      <div class="row align-items-center justify-content-between">
        <div class="col-4">
          <h1><%= c.title %></h1>
            <p class="home">
              <%= c.teaser %> &nbsp; <%= link_to 'En savoir plus...', content_path(c.id), class:"lire-plus" %>
            </p>
        </div>
        <div class="col-6 img-parent">
          <div class="img-custom">
            <div class="grayscale">
              <%= cl_image_tag c.image800x800.key %>
            </div>
          </div>
            <div class="img-hexagone"><img src="<%= image_url("masque-hexagone.png") %>"></div>
        </div>
      </div>
    </div>
    <div class="topic-banner">
      <%= cl_image_tag c.image.key %>
    </div>
    <% end %>
    <% if c.order == 3 %>
    <div id="formations" class="topic">
      <div class="row align-items-center justify-content-between">
        <div class="col-4">
          <h1><%= c.title %></h1>
            <p class="home">
              <%= c.teaser %> &nbsp; <%= link_to 'En savoir plus...', content_path(c.id), class:"lire-plus" %>
            </p>
        </div>
        <div class="col-6 img-parent">
          <div class="img-custom">
            <div class="grayscale">
              <%= cl_image_tag c.image800x800.key %>
            </div>
          </div>
            <div class="img-hexagone"><img src="<%= image_url("masque-hexagone.png") %>"></div>
        </div>
      </div>
    </div>
    <div class="topic-banner">
      <%= cl_image_tag c.image.key %>
    </div>
    <% end %>
    <% if c.order == 4 %>
    <div id="parrainage" class="topic">
      <div class="row align-items-center justify-content-between">
        <div class="col-4">
          <h1><%= c.title %></h1>
            <p class="home">
              <%= c.teaser %> &nbsp; <%= link_to 'En savoir plus...', content_path(c.id), class:"lire-plus" %>
            </p>
        </div>
        <div class="col-6 img-parent">
          <div class="img-custom">
            <div class="grayscale">
              <%= cl_image_tag c.image800x800.key %>
            </div>
          </div>
            <div class="img-hexagone"><img src="<%= image_url("masque-hexagone.png") %>"></div>
        </div>
      </div>
    </div>
    <div class="topic-banner">
      <%= cl_image_tag c.image.key %>
    </div>
    <% end %>
    <% if c.order == 5 %>
    <div id="entreprises" class="topic">
      <div class="row align-items-center justify-content-between">
        <div class="col-4">
          <h1><%= c.title %></h1>
            <p class="home">
              <%= c.teaser %> &nbsp; <%= link_to 'En savoir plus...', content_path(c.id), class:"lire-plus" %>
            </p>
        </div>
        <div class="col-6 img-parent">
          <div class="img-custom">
            <div class="grayscale">
              <%= cl_image_tag c.image800x800.key %>
            </div>
          </div>
            <div class="img-hexagone"><img src="<%= image_url("masque-hexagone.png") %>"></div>
        </div>
      </div>
    </div>
    <div class="topic-banner">
      <%= cl_image_tag c.image.key %>
    </div>
    <% end %>
    <% if c.order == 6 %>
    <div id="produits" class="topic">
      <div class="row align-items-center justify-content-between">
        <div class="col-4">
          <h1><%= c.title %></h1>
            <p class="home">
              <%= c.teaser %> &nbsp; <%= link_to 'En savoir plus...', content_path(c.id), class:"lire-plus" %>
              <!-- Begin Mailchimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/slim-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
  #mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
  /* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
     We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://terreatair.us19.list-manage.com/subscribe/post?u=f9b7bfa34d745b5a126e71ebe&amp;id=b3ce33569d" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
  <label for="mce-EMAIL">Prévenez-moi quand la boutique en ligne sera ouverte</label>
  <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="e-mail" required>
    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_f9b7bfa34d745b5a126e71ebe_b3ce33569d" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Enregistrer" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->
            </p>
        </div>
        <div class="col-6 img-parent">
          <div class="img-custom">
            <div class="grayscale">
              <%= cl_image_tag c.image800x800.key %>
            </div>
          </div>
            <div class="img-hexagone"><img src="<%= image_url("masque-hexagone.png") %>"></div>
        </div>
      </div>
    </div>
    <div class="topic-banner">
      <%= cl_image_tag c.image.key %>
    </div>
    <% end %>
    <% if c.order == 7 %>
    <div id="bien-etre" class="topic">
      <div class="row align-items-center justify-content-between">
        <div class="col-4">
          <h1><%= c.title %></h1>
            <p class="home">
              <%= c.teaser %> &nbsp; <%= link_to 'En savoir plus...', content_path(c.id), class:"lire-plus" %>
            </p>
        </div>
        <div class="col-6 img-parent">
          <div class="img-custom">
            <div class="grayscale">
              <%= cl_image_tag c.image800x800.key %>
            </div>
          </div>
            <div class="img-hexagone"><img src="<%= image_url("masque-hexagone.png") %>"></div>
        </div>
      </div>
    </div>
    <div class="topic-banner">
      <%= cl_image_tag c.image.key %>
    </div>
    <% end %>
    <% if c.order == 8 %>
    <div id="volontariat" class="topic">
      <div class="row align-items-center justify-content-between">
        <div class="col-4">
          <h1><%= c.title %></h1>
            <p class="home">
              <%= c.teaser %> &nbsp; <%= link_to 'En savoir plus...', content_path(c.id), class:"lire-plus" %>
            </p>
        </div>
        <div class="col-6 img-parent">
          <div class="img-custom">
            <div class="grayscale">
              <%= cl_image_tag c.image800x800.key %>
            </div>
          </div>
            <div class="img-hexagone"><img src="<%= image_url("masque-hexagone.png") %>"></div>
        </div>
      </div>
    </div>
    <div class="topic-banner">
      <%= cl_image_tag c.image.key %>
    </div>
    <% end %>
    <% if c.order == 9 %>
    <div id="galerie" class="topic">
      <div class="row align-items-center justify-content-between">
        <div class="col-4">
          <h1><%= c.title %></h1>
            <p class="home">
              <%= c.teaser %> &nbsp; <%= link_to 'En savoir plus...', content_path(c.id), class:"lire-plus" %>
            </p>
        </div>
        <div class="col-6 img-parent">
          <div class="img-custom">
            <div class="grayscale">
              <%= cl_image_tag c.image800x800.key %>
            </div>
          </div>
            <div class="img-hexagone"><img src="<%= image_url("masque-hexagone.png") %>"></div>
        </div>
      </div>
    </div>
    <div class="topic-banner">
      <%= cl_image_tag c.image.key %>
    </div>
    <% end %>
    <% if c.order == 10 %>
    <div id="contact" class="topic">
      <div class="row align-items-center justify-content-between">
        <div class="col-4">
          <h1><%= c.title %></h1>
            <p class="home">
              <%= simple_format(c.teaser.html_safe) %>
            </p>
        </div>
        <div class="col-6 img-parent">
          <div class="img-custom">
            <div class="grayscale">
              <%= cl_image_tag c.image800x800.key %>
            </div>
          </div>
            <div class="img-hexagone"><img src="<%= image_url("masque-hexagone.png") %>"></div>
        </div>
      </div>
    </div>
    <div class="topic-banner">
      <%= cl_image_tag c.image.key %>
    </div>
    <% end %>
  <% end %>

app/views/contents/new.html.erb
<div class="container margin-top">
  <h1>Créer un nouveau contenu</h1>
  <hr>
  <%= simple_form_for @content, url: contents_path do |c| %>
  <%= c.association :tags, collection: @tags, as: :check_boxes, input_html: { multiple: true}, label: 'Rubrique(s)' %>
  <%= c.input :title, label: 'Titre' %>
  <%= c.input :teaser, label: 'Teaser' %>
  <%= c.input :body, label:'Corps de texte' %>
  <%= c.input :links, label: 'Liens' %>
  <%= c.input :image, as: :file, label: 'Image pour le format "banner"' %>
  <%= c.input :image800x800, as: :file, label: 'Image pour le format carré' %>
  <%= c.input :order, as: :integer, label: "Ordre en page d'accueil" %>
  <%= c.input :status, label: 'Statut', collection: ['draft', 'published', 'archived'], default:'published' %>
  <%= c.submit "Créer" %>
  <% end %>
</div>

app/views/contents/show.html.erb
<div class="container-content-title">
<div class="show-banner" style="background-image: url('<%= cl_image_path @content.image.key %>'); filter: grayscale(1);">
</div>
 <div class="container content-title">
  <h1 class="content-title"><%= @content.title %></h1>
 </div>
</div>

<div class="container">
<!--   <p><%= @content.status %></p> -->
<!--   <p><%= cl_image_tag @content.image.key %></p> -->
  <p class="teaser"><%= @content.teaser %></p>
  <p><%= simple_format(@content.body.html_safe) %></p>
  <p><%= @content.links %></p>
<!--   <p>Ecrit par <i><%= @content.user.firstname %></i>, le <%= @content.created_at %></p> -->
<hr>
  <% if user_signed_in? %>
    <% if current_user.admin == true %>
      <%= button_to "Supprimer", content_path(@content),
                  method: :delete,
                  data: { confirm: "Veuillez confirmer la suppression !" },
                 :id => "delete", class:"btn btn-danger" %>
    <% end %>
  <% end %>
  <%= @content.tags%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Terreatair</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link href="https://fonts.googleapis.com/css2?family=Amatic+SC:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.14/css/all.css">
    <!-- MAILCHIMP -->
    <script id="mcjs">!function(c,h,i,m,p){m=c.createElement(h),p=c.getElementsByTagName(h)[0],m.async=1,m.src=i,p.parentNode.insertBefore(m,p)}(document,"script","https://chimpstatic.com/mcjs-connected/js/users/f9b7bfa34d745b5a126e71ebe/00a64fe971cc1d2225a85b408.js");</script>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>

    <%= render 'shared/footer' %>


    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/pages/admin.html.erb
<div class="container margin-top">
  <h1>Administration du site</h1>
  <hr>
  <ol>
    <li> <%= link_to 'Gérer les contenus', '/admin/contents' %> </li>
    <li> <%= link_to 'Gérer les rubriques', '/tags' %> </li>
  </ol>
</div>

app/views/pages/home.html.erb
home

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/terreatair" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/Terreatair.be" target="_blank"><i class="fab fa-facebook"></i></a>
    <%= link_to I18n.t('mentions-legales'), "/contents/16"%>
  </div>
  <div class="footer-copyright">
    <% if user_signed_in? %>
      <% if current_user.admin == true %>
        <div class="footer-links">
          <%= link_to "Admin", "/admin" %>
          <%= link_to "Déconnexion", destroy_user_session_path, method: :delete%>
        </div>
      <% end %>
      <% else %>
      <li class="footer-links">
        <%= link_to new_user_session_path do %>
          <i class="far fa-user fa-fw"></i>
        <% end %>
      <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>
<!-- BURGER BUTTON MOBILE -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
<!-- END -->

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <!-- TOPICS MENU -->
      <li class="nav-item">
        <%= link_to I18n.t('home.poject'), "/#projet", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to I18n.t('home.animations'), "/#animations", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to I18n.t('home.formations'), "/#formations", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to I18n.t('home.sponsorship'), "/#parrainage", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to I18n.t('home.companies'), "/#entreprises", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to I18n.t('home.products'), "/#produits", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to I18n.t('home.health'), "/#bien-etre", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to I18n.t('home.volunteering'), "/#volontariat", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to I18n.t('home.gallery'), "#galerie", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to I18n.t('home.contact'), "/#contact", class: "nav-link" %>
      </li>
      <!-- END TOPICS MENU -->
      <li class="nav-item dropdown">
        <!-- LANGUAGES MENU -->
<!--         <a class="btn btn-outline-secondary btn-round btn-locale" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" title="Langue">
          <%= I18n.locale %>
        </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "FR", "/fr", class: "dropdown-item" %>
            <%= link_to "NL", "/nl", class: "dropdown-item" %>
            <%= link_to "EN", "/en", class: "dropdown-item" %>
          </div>
      </li> -->
      <!-- END LANGUAGES MENU -->
      <!-- USER MENU -->
<!--       <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="btn btn-outline-secondary btn-round" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" title=I18n.t('home.myaccount')>
            <i class="fas fa-user fa-fw"></i>
          </a>
        </li>
        <li class="nav-item dropdown">
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to I18n.t('home.logout'), destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.admin == true %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Contenus", "/admin/contents", class: "dropdown-item" %>
            </div>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to new_user_session_path , class: "btn btn-outline-secondary btn-round " do %>
            <i class="far fa-user fa-fw"></i>
          <% end %>
        </li>
      <% end %> -->
      <!-- END USER MENU -->
    </ul>
  </div>
</div>

app/views/shared/_related-content.html.erb
<% @contents.each do |c| %>
  <% if c.tags == current_page(params: tags) %>
  <%= c.title %>
  <% end %>
<% end %>

app/views/tags/edit.html.erb
<div class="container margin-top">
  <h1>Créer une catégorie</h1>
  <hr>
  <%= simple_form_for @tag, url: tags_path, method: :patch do |c| %>
  <%= c.input :title, label: 'Titre' %>
  <%= c.input :description, label: 'Description' %>
  <%= c.submit "Enregistrer", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/tags/index.html.erb
<div class="container margin-top">
    <div class="row">
    <div class="col-8">
      <h1 class="title-admin">Gestion des rubriques</h1>
    </div>
    <div class="col-4">
      <%= link_to 'Ajouter une rubrique', new_tag_path, class:'btn btn-primary btn-right' %>
    </div>
  </div>
  <hr>
    <% @tags.each do |t| %>
      <div class="row admin-row">
        <div class="col">
         <b><%= t.title %></b>
        </div>
        <div class="col-6">
          <%= t.description %>
        </div>
      <div class="col-2">
        <%= link_to edit_tag_path(t.id), title:"Modifier", class: "btn btn-primary" do %>
          Modifier
        <% end %>
      </div>
      <div class="col-1">
              <%= button_to "Supprimer", tag_path(t.id),
                  method: :delete,
                  data: { confirm: "Veuillez confirmer la suppression !" },
                 :id => "delete", class:"btn btn-danger" %>
      </div>
      </div>
    <% end %>
</div>

app/views/tags/new.html.erb
<div class="container margin-top">
  <h1>Créer une catégorie</h1>
  <hr>
  <%= simple_form_for @tag, url: tags_path do |c| %>
  <%= c.input :title, label: 'Titre' %>
  <%= c.input :description, label: 'Description' %>
  <%= c.submit "Enregistrer", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container margin-top">
  <h1><%= @user.firstname %> <%=@user.name %></h1>
  <p> <%= @user.email %></p>
</div>

app/views/users/sign_in.html.erb
sign_in.html.erb